// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: pb/richmedia/ntv2.proto

package richmedia

type NTV2RichMediaReq struct {
	ReqHead  *MultiMediaReqHead `protobuf:"bytes,1,opt"`
	Download *DownloadReq       `protobuf:"bytes,3,opt"`
	_        [0]func()
}

type MultiMediaReqHead struct {
	Common *CommonHead `protobuf:"bytes,1,opt"`
	Scene  *SceneInfo  `protobuf:"bytes,2,opt"`
	Client *ClientMeta `protobuf:"bytes,3,opt"`
	_      [0]func()
}

type CommonHead struct {
	RequestId uint32 `protobuf:"varint,1,opt"`
	Command   uint32 `protobuf:"varint,2,opt"`
	_         [0]func()
}

type SceneInfo struct {
	RequestType  uint32       `protobuf:"varint,101,opt"`
	BusinessType uint32       `protobuf:"varint,102,opt"`
	SceneType    uint32       `protobuf:"varint,200,opt"`
	C2C          *C2CUserInfo `protobuf:"bytes,201,opt"`
	Group        *NTGroupInfo `protobuf:"bytes,202,opt"`
	_            [0]func()
}

type ClientMeta struct {
	AgentType uint32 `protobuf:"varint,1,opt"`
	_         [0]func()
}

type C2CUserInfo struct {
	AccountType uint32 `protobuf:"varint,1,opt"`
	TargetUid   string `protobuf:"bytes,2,opt"`
	_           [0]func()
}

type NTGroupInfo struct {
	GroupUin uint32 `protobuf:"varint,1,opt"`
	_        [0]func()
}

type DownloadReq struct {
	Node *IndexNode `protobuf:"bytes,1,opt"`
	_    [0]func()
}

type IndexNode struct {
	Info     *FileInfo `protobuf:"bytes,1,opt"`
	FileUuid string    `protobuf:"bytes,2,opt"`
	StoreId  uint32    `protobuf:"varint,3,opt"`
	_        [0]func()
}

type FileInfo struct {
	Type *FileType `protobuf:"bytes,5,opt"`
	Time uint32    `protobuf:"varint,8,opt"`
	_    [0]func()
}

type FileType struct {
	Type        uint32 `protobuf:"varint,1,opt"`
	VoiceFormat uint32 `protobuf:"varint,4,opt"`
	_           [0]func()
}

type NTV2RichMediaRsp struct {
	MediaResp *MediaResp `protobuf:"bytes,4,opt"`
	_         [0]func()
}

type MediaResp struct {
	DownloadResp *DownloadResp `protobuf:"bytes,3,opt"`
	_            [0]func()
}

type DownloadResp struct {
	Rkey string        `protobuf:"bytes,1,opt"`
	Info *DownloadInfo `protobuf:"bytes,3,opt"`
	_    [0]func()
}

type DownloadInfo struct {
	Domain  string `protobuf:"bytes,1,opt"`
	UrlPath string `protobuf:"bytes,2,opt"`
	_       [0]func()
}
